apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-pv-provisioning-demo
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-demo
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Mi
  storageClassName: snapshot-promoter
