kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: cephfs
provisioner: kubernetes.io/cephfs
parameters:
    monitors: 172.24.0.4:6789
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: "kube-system"

