kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: run-glusterblock-provisioner
subjects:
  - kind: ServiceAccount
    name: glusterblock-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: glusterblock-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
