#!/bin/bash

# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

IMAGEID=$( sudo docker images -q ${DIMAGE}:latest )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  sudo docker login -u "${DNAME}" -p "${DPASS}"; 
  sudo docker push ${DIMAGE}:latest ; 
  if [ ! -z "${TRAVIS_TAG}" ] ; 
  then
    #Push the release tag image to docker hub repository
    #When a git hub is tagged with a release, the travis will 
    #hold the release tag in env TRAVIS_TAG
    sudo docker tag ${IMAGEID} ${DIMAGE}:${TRAVIS_TAG}
    sudo docker push ${DIMAGE}:${TRAVIS_TAG}; 
    sudo docker tag ${IMAGEID} ${DIMAGE}:latest
    sudo docker push ${DIMAGE}:latest; 
  fi;
else
  echo "No docker credentials provided. Skip uploading ${DIMAGE}:ci to docker hub"; 
fi;
