kind: Pod
apiVersion: v1
metadata:
  name: flex-provisioner
spec:
  serviceAccountName: flex-provisioner
  containers:
    - name: flex-provisioner
      image: childsb/flex-provisioner
      securityContext:
      args:
        - "-provisioner=external/flex-simple"
        - "-execCommand=/opt/storage/flex-provision.sh"
      imagePullPolicy: "IfNotPresent"
