{{- if .Values.common.rbac }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.daemonset.serviceAccount }}
  namespace: {{ .Values.common.namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ replace "+" "_" .Chart.Version | printf "%s-%s" .Chart.Name }}
{{- end }}
