apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glusterblock-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: glusterblock-provisioner
    spec:
      containers:
        -
          env:
            -
              name: PROVISIONER_NAME
              value: gluster.org/glusterblock
          image: "quay.io/external_storage/glusterblock-provisioner:latest"
          name: glusterblock-provisioner
