apiVersion: v1
kind: Pod
metadata: 
  name: glusterblock-provisioner
spec: 
  containers: 
    env:
      name: PROVISIONER_NAME
      value: gluster.org/glusterblock
    image: "quay.io/external_storage/glusterblock-provisioner:latest"
    name: glusterblock-provisioner
