# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: v1
kind: ReplicationController
metadata:
  name: gluster-busybox
spec:
  replicas: 2
  selector:
    name: gluster-busybox
  template:
    metadata:
      labels:
        name: gluster-busybox
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: gluster
            mountPath: "/mnt"
      volumes:
      - name: gluster
        persistentVolumeClaim:
          claimName: gluster-simple-claim
