---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim-on-gluster-subvol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gluster-subvol
