kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cinder-standalone-provisioner
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cinder-standalone-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cinder-standalone-provisioner
  apiGroup: rbac.authorization.k8s.io
