apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cinder-standalone-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cinder-standalone-provisioner
subjects:
- kind: ServiceAccount
  name: cinder-standalone-provisioner
