apiVersion: v1
kind: Secret
metadata:
  name: iscsi-targetd-chap-secret
type: "kubernetes.io/iscsi-chap"
data:
  discovery.sendtargets.auth.username: aW5pdGlhdG9yX2Rpc2NvdmVyeV91c2Vy
  discovery.sendtargets.auth.password: aW5pdGlhdG9yX2Rpc2NvdmVyeV9wYXNzd29yZA==
  discovery.sendtargets.auth.username_in: dGFyZ2V0X2Rpc2NvdmVyeV91c2Vy
  discovery.sendtargets.auth.password_in: dGFyZ2V0X2Rpc2NvdmVyeV9wYXNzd29yZA==
  node.session.auth.username: aW5pdGlhdG9yX3Nlc3Npb25fdXNlcg==
  node.session.auth.password: aW5pdGlhdG9yX3Nlc3Npb25fcGFzc3dvcmQ=
  node.session.auth.username_in: dGFyZ2V0X3Nlc3Npb25fdXNlcg==
  node.session.auth.password_in: dGFyZ2V0X3Nlc3Npb25fcGFzc3dvcmQ=