kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-glusterfile-provisioner
subjects:
  - kind: ServiceAccount
    name: glusterfile-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: glusterfile-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
