---
- hosts: nodes
  tasks:
  - name: Install iscsi-initiator-utils
    yum: 
      name: iscsi-initiator-utils
      state: latest
  - name: Install device-mapper-multipath
    yum:
      name: device-mapper-multipath
      state: latest
  - name: Write iscsi initiator name
    lineinfile:
      regexp: '^(InitiatorName=).*'
      dest: /etc/iscsi/initiatorname.iscsi
      line: '\1{{ iscsi_initiator_name }}'
      state: present
      backrefs: yes
  - name: Write multipath conf file
    copy:
      src: multipath.conf
      dest: /etc/multipath.conf
  - name: Enable iscsid Service
    service:
      name: iscsid
      enabled: yes
      state: started
  - name: enable multipathd service
    service:
      state: started
      enabled: yes
      name: multipathd
