apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-pv-provisioning-demo
  namespace: myns
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-1
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 8Gi
  storageClassName: snapshot-promoter

