kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claimheketi
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterblock"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
