apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: digitalocean-provisioner
  name: digitalocean-provisioner
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digitalocean-provisioner
  template:
    metadata:
      labels:
        app: digitalocean-provisioner
    spec:
      containers:
      - env:
        - name: DIGITALOCEAN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: access-token
              name: digitalocean
        image: quay.io/external_storage/digitalocean-provisioner
        imagePullPolicy: Always
        name: digitalocean-provisioner
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
      serviceAccount: digitalocean-provisioner
