# Only valid for Kubernetes 1.9+
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scsi
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-nvme
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
