apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: standalone-cinder-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: standalone-cinder-provisioner
    spec:
      containers:
      - name: standalone-cinder-provisioner
        image: "quay.io/external_storage/standalone-cinder-provisioner:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: OS_CINDER_ENDPOINT
          value: http://192.168.2.17:8776/v2
        - name: OS_USERNAME
          value: admin
        - name: OS_TENANT_NAME
          value: admin
